FROM golang:1.21-alpine AS builder
ENV CGO_ENABLED=0
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o fizzbuzz main.go

FROM gcr.io/distroless/static
COPY --from=builder /app/fizzbuzz /fizzbuzz
CMD ["/fizzbuzz", "serve"]


//